package com.kj.commdityinfo.mapper;

import com.kj.commdityinfo.bean.ItemInfo;
import com.kj.commdityinfo.bean.ex.ItemInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    long countByExample(ItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int deleteByExample(ItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer iteminfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int insert(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int insertSelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    List<ItemInfo> selectByExample(ItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    ItemInfo selectByPrimaryKey(Integer iteminfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ItemInfo record, @Param("example") ItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ItemInfo record, @Param("example") ItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteminfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemInfo record);
}